// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRKf1kQWQRUYcPdWHQneTyDQVxBdGiDV8',
    appId: '1:797719357072:web:96fb3c1721a280b5d31a15',
    messagingSenderId: '797719357072',
    projectId: 'final-year-4-cs',
    authDomain: 'final-year-4-cs.firebaseapp.com',
    storageBucket: 'final-year-4-cs.appspot.com',
    measurementId: 'G-T9DQENPY7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvpcpeRvZqRpeeV97_lZXwee5TlwkC1xY',
    appId: '1:797719357072:android:3f65faf1ebcfb4a2d31a15',
    messagingSenderId: '797719357072',
    projectId: 'final-year-4-cs',
    storageBucket: 'final-year-4-cs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCHRMGal9RbIaVg-9P46wotK1N0tipuaY',
    appId: '1:797719357072:ios:525e5310c08bc9d0d31a15',
    messagingSenderId: '797719357072',
    projectId: 'final-year-4-cs',
    storageBucket: 'final-year-4-cs.appspot.com',
    iosClientId: '797719357072-d64q0j9vju91ougelvkjpslvmlqqa4h7.apps.googleusercontent.com',
    iosBundleId: 'com.finalyear4cs.finalYear4cs',
  );
}
